# Generated by Django 6.0.dev20250307143456 on 2025-05-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_chess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='move_history',
            field=models.TextField(default='[]'),
        ),
    ]
